test_arguments:
  data1: "messages.csv"
  epochs1: 3
  data2: "messages.csv"
  epochs2: -5
  data3: "news_articles.csv"
  epochs3: 260
  data4: "messages.csv"
  data5: "image.csv"
  #data6: "large_data.csv"
