test_arguments:
  key: ""
  secret: ""
  s3_endpoint: "https://s3.amazonaws.com"
  region_name: "us-east-1"
  bucket_name1: "test-bucket-98928776"
  bucket_name2: "test-bucket"
  bucket_name3: "test-bucket-98928777"
  obj_name1: "sample.txt"
  obj_name2: "file.txt"
  obj_name3: "file2.txt"
  obj_name4: "testfile.txt"
  incorrect_key: "jiojjjjjjjdcvbnj"
  incorrect_secret: "dfghjkmndrtyuknftyj"