name: Unit Tests for Chatbot Inference

on:
  push:
    branches:
      - main
      - add-unittests
    paths:
      - chatbot_inference/**
      
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install libs
        run: |
          python -m pip install --upgrade pip
          pip install -r chatbot_inference/requirements.txt
        working-directory: ${{ env.GITHUB_WORKSPACE }}
      - name: Execute unit tests
        run: cd chatbot_inference && python unittest_predict.py
        working-directory: ${{ env.GITHUB_WORKSPACE }}
