name: Unit Tests for Chatbot Train # testing

env:
    TEST_DIRECTORY: chatbot_train
on:
  push:
    branches:
      - main
      - add-unittests
    paths:
      - ${TEST_DIRECTORY}/**
      
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install libs
        run: |
          sudo mkdir /cnvrg; pip install -r ${TEST_DIRECTORY}/requirements.txt
      - name: Execute unit tests
        run: |
          cd ${TEST_DIRECTORY}; find . -name unittest*.py -exec sudo python3 {} +
